ImageGallery.Client/ViewModels/AddImageViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ImageGallery.IDP.Client.ViewModels
{
    public class AddImageViewModel
    {
        public List<IFormFile> Files { get; set; } = new List<IFormFile>();

        [Required]
        public string Title { get; set; }

        public AddImageViewModel(string title, List<IFormFile> files)
        {
            Title = title;
            Files = files;
        }

        public AddImageViewModel()
        {

        }
    }
}

ImageGallery.Client/ViewModels/EditImageViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ImageGallery.IDP.Client.ViewModels
{
    public class EditImageViewModel
    {
        [Required]
        public string Title { get; set; } = string.Empty;

        [Required]
        public Guid Id { get; set; }  
    }
}

ImageGallery.Client/Controllers/GalleryController.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using ImageGallery.IDP.Client.ViewModels;
using ImageGallery.IDP.Model;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;

namespace ImageGallery.IDP.Client.Controllers;

[Authorize]
public class GalleryController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly ILogger<GalleryController> _logger;

    public GalleryController(IHttpClientFactory httpClientFactory,
        ILogger<GalleryController> logger)
    {
        _httpClientFactory = httpClientFactory ??
                             throw new ArgumentNullException(nameof(httpClientFactory));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public async Task<IActionResult> Index()
    {
        await LogIdentityInformation();
        
        var httpClient = _httpClientFactory.CreateClient("APIClient");

        var request = new HttpRequestMessage(
            HttpMethod.Get,
            "/api/images/");

        var response = await httpClient.SendAsync(
            request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

        response.EnsureSuccessStatusCode();
        

        using (var responseStream = await response.Content.ReadAsStreamAsync())
        {
            var images = await JsonSerializer.DeserializeAsync<List<Image>>(responseStream);
            return View(new GalleryIndexViewModel(images ?? new List<Image>()));
        }
    }

    public async Task<IActionResult> EditImage(Guid id)
    {
        var httpClient = _httpClientFactory.CreateClient("APIClient");

        var request = new HttpRequestMessage(
            HttpMethod.Get,
            $"/api/images/{id}");

        var response = await httpClient.SendAsync(
            request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

        response.EnsureSuccessStatusCode();

        using (var responseStream = await response.Content.ReadAsStreamAsync())
        {
            var deserializedImage = await JsonSerializer.DeserializeAsync<Image>(responseStream);

            if (deserializedImage == null)
            {
                throw new Exception("Deserialized image must not be null.");
            }

            var editImageViewModel = new EditImageViewModel()
            {
                Id = deserializedImage.Id,
                Title = deserializedImage.Title
            };

            return View(editImageViewModel);
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditImage(EditImageViewModel editImageViewModel)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        // create an ImageForUpdate instance
        var imageForUpdate = new ImageForUpdate(editImageViewModel.Title);

        // serialize it
        var serializedImageForUpdate = JsonSerializer.Serialize(imageForUpdate);

        var httpClient = _httpClientFactory.CreateClient("APIClient");

        var request = new HttpRequestMessage(
            HttpMethod.Put,
            $"/api/images/{editImageViewModel.Id}")
        {
            Content = new StringContent(
                serializedImageForUpdate,
                System.Text.Encoding.Unicode,
                "application/json")
        };

        var response = await httpClient.SendAsync(
            request, HttpCompletionOption.ResponseHeadersRead);

        response.EnsureSuccessStatusCode();

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> DeleteImage(Guid id)
    {
        var httpClient = _httpClientFactory.CreateClient("APIClient");

        var request = new HttpRequestMessage(
            HttpMethod.Delete,
            $"/api/images/{id}");

        var response = await httpClient.SendAsync(
            request, HttpCompletionOption.ResponseHeadersRead);

        response.EnsureSuccessStatusCode();

        return RedirectToAction("Index");
    }
 
    [Authorize(Policy = "UserCanAddImage")]
    public IActionResult AddImage()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "UserCanAddImage")]
    public async Task<IActionResult> AddImage(AddImageViewModel addImageViewModel)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        // create an ImageForCreation instance
        ImageForCreation? imageForCreation = null;

        // take the first (only) file in the Files list
        var imageFile = addImageViewModel.Files.First();

        if (imageFile.Length > 0)
        {
            using (var fileStream = imageFile.OpenReadStream())
            using (var ms = new MemoryStream())
            {
                fileStream.CopyTo(ms);
                imageForCreation = new ImageForCreation(
                    addImageViewModel.Title, ms.ToArray());
            }
        }

        // serialize it
        var serializedImageForCreation = JsonSerializer.Serialize(imageForCreation);

        var httpClient = _httpClientFactory.CreateClient("APIClient");

        var request = new HttpRequestMessage(
            HttpMethod.Post,
            $"/api/images")
        {
            Content = new StringContent(
                serializedImageForCreation,
                System.Text.Encoding.Unicode,
                "application/json")
        };

        var response = await httpClient.SendAsync(
            request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

        response.EnsureSuccessStatusCode();

        return RedirectToAction("Index");
    }
    
    public async Task LogIdentityInformation()
    {
        // get the saved identity token
        var identityToken = await HttpContext
            .GetTokenAsync(OpenIdConnectParameterNames.IdToken);

        // get the saved access token
        var accessToken = await HttpContext
            .GetTokenAsync(OpenIdConnectParameterNames.AccessToken);

        // get the refresh token
        var refreshToken = await HttpContext
            .GetTokenAsync(OpenIdConnectParameterNames.RefreshToken);

        var userClaimsStringBuilder = new StringBuilder();
        foreach (var claim in User.Claims)
        {
            userClaimsStringBuilder.AppendLine(
                $"Claim type: {claim.Type} - Claim value: {claim.Value}");
        }

        // log token & claims
        _logger.LogInformation($"Identity token & user claims: " +
                               $"\n{identityToken} \n{userClaimsStringBuilder}");
        _logger.LogInformation($"Access token: " +
                               $"\n{accessToken}");
        _logger.LogInformation($"Refresh token: " +
                               $"\n{refreshToken}");
    }
}

ImageGallery.Client/Views/Gallery/AddImage.cshtml
@model ImageGallery.IDP.Client.ViewModels.AddImageViewModel

<h2 class="leftMarginSmaller">Add Image</h2>

<form asp-action="AddImage" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">

    <div class="form-horizontal leftMarginDefault">
        
        <div class="form-group">
            <div>You image's title</div>
            <input asp-for="Title" class="form-control" />
        </div>
        
        <div class="form-group">
            <div>The image file</div>
            <input asp-for="Files" type="file" class="form-control" accept=".jpg,.jpeg"/>
        </div>

        <div class="form-group">
            <div>
                <input type="submit" class="btn btn-primary" value="Add image" />
            </div>
        </div>
    </div>
</form>

ImageGallery.Client/Views/Gallery/EditImage.cshtml
@model ImageGallery.IDP.Client.ViewModels.EditImageViewModel

<h2 class="leftMarginSmaller">Edit Image Title</h2>

<form asp-action="EditImage" method="post" class="form-horizontal" role="form">

    <div class="form-horizontal leftMarginDefault">
        
        <div class="form-group">
            <div>You image's title</div>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <div>
                <input type="submit" class="btn btn-primary" value="Change title" />
            </div>
        </div>
    </div>
</form>

ImageGallery.Client/Views/Gallery/Index.cshtml
@model ImageGallery.IDP.Client.ViewModels.GalleryIndexViewModel

<div class="bottomMarginDefault">
</div>

<div class="container">
      <div class="row">
    @foreach (var item in Model.Images)
    {
       <div class="pull-left col-md-4">            
            <div>
                <img class="thumbnailImage" src="@("https://localhost:7075/images/" + item.FileName)" />
            </div>
            <div>
                <div class="h6 topMarginSmall">@item.Title</div>
                <div class="bottomMarginDefault">
                    <a asp-action="EditImage" asp-controller="Gallery" asp-route-id="@item.Id">Edit title</a> |
                    <a asp-action="DeleteImage" asp-controller="Gallery" asp-route-id="@item.Id">Delete image</a>
                </div>
            </div>
        </div>
    }
    </div>
</div> 